title: Ruby on Rails
description: A web-app framework that includes everything needed to create database-backed web applications according to the Model-View-Controller (MVC) pattern.
twitter: rails
feed_path: /feed.xml
world_title: Rails World - 2023

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

collections:
  pages:
    output: true
    permalink: "/:name"
  world_speakers:
    output: true
    permalink: "/world/:path"
  world_sessions:
    output: true
    permalink: "/world/:path"


defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "/:year/:i_month/:i_day/:title"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "world_speakers"
    values:
      layout: "world/speaker"
  - scope:
      path: ""
      type: "world_sessions"
    values:
      layout: "world/session"
  - scope:
      path: "world/2023"
    values:
      description: October 5 & 6 - Beurs van Berlage, Amsterdam, NL

markdown: kramdown
highlighter: rouge
paginate: 10
paginate_path: "/blog/page/:num"
sass:
  style: :compressed
